security:
  basic:
    enabled: false
spring:
  profiles: dev
  ldap:
    urls: ldap://localhost:389
    base: ou=users,dc=mycompany,dc=com
    username: cn=admin,dc=mycompany,dc=com
    password: admin
    anonymousReadOnly: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5
db:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/springboot?characterEncoding=utf-8&useSSL=false
  username: root
  password:
  maxActive: 500
person:
  lastName: bigD
  age: 20
  boss: false
  birth: 2017/01/02
  maps: {k1: v1,k2: v2}
  lists:
    - zhangsan
    - lisi
    - wangwu
  dog:
    name: wangwang
    age: 6
server:
  port: 8080
